"""null address values

Revision ID: 50793b512aae
Revises: ecaf0f70e066
Create Date: 2026-02-13 08:44:37.916527

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50793b512aae'
down_revision: Union[str, Sequence[str], None] = 'ecaf0f70e066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
